### ISSUE TITLE
[feature request] Missing deploy.ts for delegator example

### ISSUE THREAD

**Issue by catomasa** [patractlabs/redspot#100]
I'm attempting to deploy a contract with multiple parameters, which deploys another contract. The delegator contract would be a good example for me to get started, but that is missing a `scripts/deploy.ts` file.

**Comment by atenjin** [comment]
It will wait untail we re-design the template part. In new template part can support different template project instantiation and related scripts/tests.

**Comment by ii-ii-ii** [comment]
Yes, we will provide examples. But our examples can't cover every case. You can try to write your own code for deployment.If you encounter problems, we will provide help. For documentation, you can refer to [polkadotjs](https://polkadot.js.org/docs/) and [redspot's documentation](https://substrate-contracts-book-patract.vercel.app/en/redspot/plugin.html#redspot-patract), the English version of our documentation is machine translated for now and will be improved later.

**Comment by ii-ii-ii** [comment]
@catomasa  https://github.com/patractlabs/redspot/blob/master/examples/delegator/scripts/deploy.ts This is an example of  delegator deployment
