### ISSUE TITLE
Handling types with the same name

### ISSUE THREAD

**Issue by KaiserKarel** [patractlabs/redspot#125]
I've got 2 contracts which expose types with identical names. Is there a way to add namespacing so that I can add both types to the redspot config?

```
// contract 1
pub struct Foo {
   balance: Balance,
   name: String,
}

// contract 2 
pub struct Foo {
   balance: Balance,
   name: i64,
   date: Timestamp
}

**Comment by ii-ii-ii** [comment]
Not yet, you can change the type name, such as Contract1Foo, Contract2Foo
