### ISSUE TITLE
Value of a storage field of type string is queried incorrectly in test

### ISSUE THREAD

**Issue by tk-o** [patractlabs/redspot#131]
I am using a simple Erc20 smart contract, that allows including its name and symbol. [Here's how I define getters for these two fields](https://github.com/atomiklabs/decomm/blob/cross-contract-calls/contracts/erc20/lib.rs#L221-L229).

I noticed, that the value stored in the smart contract is exactly (byte by byte) the same as the one passed into the contract's constructor. So far so good.

But when I query any of these fields, I get the 2 extra bytes at the beginning of the stored value:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/3687215/126471396-e49f3f47-407f-4442-a0b9-14ca594813f7.png">

Because of these 2 extra bytes, I can't really assert equality in my tests, as the returned value is pre-fixed with 2 extra bytes.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/3687215/126471612-b50257b2-c22f-4060-acb2-8845e1c7d455.png">

Where these 2 extra bytes come from? I also tested using `Vec<u8>` as a return type for getters. Same story: the value in the contract storage is exactly the same, while the value returned into JS runtime has 2 extra bytes at the beginning.

**Comment by ii-ii-ii** [comment]
This should be a solved issue. You can try to upgrade to the latest version v0.11.9-0 （Note that it is all redspot related dependencies. including `redspot` `@redspot/patract` etc.）

**Comment by tk-o** [comment]
@ii-ii-ii, thank you for a prompt response! I'll give it a try 🤞

**Comment by tk-o** [comment]
Nice, [the dependencies update](https://github.com/atomiklabs/decomm/commit/bfc14fa3fdd3db6de0ed7277e32bb93aa0936dfb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) solved the issue. Thanks @ii-ii-ii 🤝
