### ISSUE TITLE
Error RS12: Trying to use a non-local installation of Redspot, which is not supported. Please install Redspot locally using npm or Yarn, and try again.

### ISSUE THREAD

**Issue by forgetso** [patractlabs/redspot#135]
**Redspot Version**
Master 550af156c3aa1f20625d8d2c3bb35cdf461146f3

Followed these instructions:

> The node version should be 14
> First you need to install the dependencies in the redspot root directory `yarn`
> Compile the code `yarn build`
> Go to the examples directory, e.g. `cd examples/erc20`
> Install the dependencies in the current directory `yarn`
> In the examples/erc20 directory, you can invoke the redspot commands normally. For example: `npx redspot` compile

Then ran into this issue:

> Error RS12: Trying to use a non-local installation of Redspot, which is not supported. Please install Redspot locally using npm or Yarn, and try again.

I have also tried creating a new redspot project and then running `npx redspot compile` but get the same result.

```
✗ node --version
v14.17.3
✗ yarn --version
3.0.0-rc.2
```

**Comment by ii-ii-ii** [comment]
Using npx directly does seem to have this problem, but you can use yarn scripts instead, such as `yarn test` `yarn build`.
﻿﻿They are defined in package.json. ﻿﻿https://github.com/patractlabs/redspot/blob/master/examples/erc20/package.json#L31-L33

**Comment by forgetso** [comment]
Thanks, using yarn works for me too.
