### ISSUE TITLE
Fail to Decode input when instanciate contract with create builder

### ISSUE THREAD

**Issue by PierreOssun** [patractlabs/redspot#141]
Hello,
I use` europa 0.3.2-f6da65d-x86_64-linux-gnu` as node.

When I instantiate contract in constructor with create builder, it fails to decode input (for any type: accoucId or bool):
```
  2) Instantiate
       It should instantiate dummy contract in constructor - and get account id:
     Error: createType(AccountId):: AccountId:: Decoded input doesn't match input, received 0x (0 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000 (32 bytes)
      at Object.createTypeUnsafe (node_modules/@polkadot/types/create/createType.cjs:59:18)
      at Object.dummyAccountId (node_modules/@redspot/patract/contract.js:118:27)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I did a minimalistic repo so you can investigate:
[Repo link](https://github.com/PierreOssun/ink-instanciate)

Note: When I deploy contract via Polkadot js app both cases works (I can see AccoutId and bool value)

Thanks

**Comment by ii-ii-ii** [comment]
What do you expect to return? The return result on the chain is indeed the null.
```
{
    "jsonrpc": "2.0",
    "result": {
        "debugMessage": "",
        "gasConsumed": 2659161284,
        "result": {
            "Ok": {
                "data": "0x",
                "flags": 0
            }
        }
    },
    "id": 72
}
```

**Comment by PierreOssun** [comment]
Hello @ii-ii-ii 
I refactor my code & my tests to showcase the issue when **instantiating from constructor** (instantiating from a message function works).
I also added some comments to describe our findings.
[repo](https://github.com/PierreOssun/ink-instanciate)

Repro steps:
launch  `europa 0.3.2-f6da65d-x86_64-linux-gnu` and run `europa --tmp`
and then in the project folder run `yarn test`

**Comment by atenjin** [comment]
have you meet the same error in new europa? version 0.3.4.

**Comment by ii-ii-ii** [comment]
@PierreOssun This is a known bug that has been fixed, upgrading redspot to the latest version will fix it.  Current is v0.12.2.
