### ISSUE TITLE
Allow to specify single target-dir, e.g. export CARGO_TARGET_DIR=/cache/target

### ISSUE THREAD

**Issue by sventime** [patractlabs/redspot#167]
We're using redspot in our projects, and it's great, but sometimes, during smart contract build, we want to specify the single target directory (e.g. `CARGO_TARGET_DIR=/cache/target`), for example, to optimize disk space and build time when running CI on remote servers. 

The condition in `compilerInput.ts` doesn't allow to do this. We created a small PR to fix it: #160 
Please, take a look at it, or resolve it in another way.

Thanks a lot!

**Comment by ii-ii-ii** [comment]
0.13.3 has been released
