### ISSUE TITLE
0.13.4 Release don't use updated code

### ISSUE THREAD

**Issue by xgreenx** [patractlabs/redspot#174]
Redspot 0.13.4 from the yarn package doesn't use the latest code from the 0.13.4 release.

The code in `node_modules`:
![image](https://user-images.githubusercontent.com/18346821/155706663-4009929b-a2e3-4cbb-a446-f871e08945b2.png)

The code in the 0.13.4 release:
![image](https://user-images.githubusercontent.com/18346821/155706703-69e793eb-1cc2-46c5-b94a-53b6c9190509.png)

Could you re-publish it, please?

**Comment by ii-ii-ii** [comment]
@[xgreenx](https://github.com/xgreenx) Indeed it is, I have released 13.5

**Comment by xgreenx** [comment]
Now it works, thanks

**Comment by DukeCaesar** [comment]
This issue surfaces again in the latest 0.13.6 release.

![Screenshot from 2022-04-28 00-26-48](https://user-images.githubusercontent.com/26783350/165567133-c801dbe9-4921-409f-a0d3-8728e23e80a5.png)
